src/hermite/mod.rs
src/jacobi/mod.rs
src/laguerre/mod.rs
src/legendre/mod.rs

Ran clippy and found some extraneous clone calls. 
Pattern match the reference to simplify the function call.

Remove unnecessary clones flagged by clippy

---

Cargo.toml

I think the docs.rs "gauss-quad-0.1.3 is not a library" message for version [0.1.3](https://docs.rs/crate/gauss-quad/0.1.3) might be resolved by putting the `lib` crate-type first in `Cargo.toml`?

Try and fix docs.rs "crate is not a library" message for crate

---

src/lib.rs

As commented, how to add a dependency can be looked up from crates.io

Remove instruction on how to add a dependency

---

src/hermite/mod.rs
src/jacobi/mod.rs
src/laguerre/mod.rs

Switches some calls to `as_vec().clone()` to `into()`, which could remove some clones.

Remove some clones

---

src/hermite/mod.rs
src/jacobi/mod.rs
src/laguerre/mod.rs
src/legendre/mod.rs
src/midpoint/mod.rs
src/simpson/mod.rs

This PR is my suggestion for #23, it unifies what traits are derived between all the different quadrature rules to `Debug`, `Clone` and `PartialEq`.
- `Debug`: in case someone using the library wants to print out the nodes and weights for debugging, this makes it very simple: just `println!("{quad_rule:?}");`.
- `Clone`: it's cheaper to clone an already initialized quadrature rule than computing all the nodes and weights again.
- `PartialEq`: easy way to check if two different instantiations of the same rule are the same. Currently only some rules can be checked for equality by checking if all the member fields are the same.

Derive `Clone`, `Debug` and `PartialEq` for all quadrature structs

---

README.md
src/gamma.rs
src/gaussian_quadrature.rs
src/hermite/mod.rs
src/jacobi/mod.rs
src/laguerre/mod.rs
src/legendre/mod.rs
src/lib.rs
src/midpoint/mod.rs
src/simpson/mod.rs

Feel free to ignore this PR as this might be something you disagree with or want to do yourself, but I have 
- Removed the use of language features in the documentation that used to be necessary (e.g. `extern crate ...` when importing a crate, or `fn main() { ... }` in tests) 
- Added docstrings to all the submodules (`laguerre`, `hermite`, etc.) that try to adhere to the style of the crate, and contain an example that is tested.
- Added docstrings to all the quadrature structs (e.g. `GaussHermite`) that contain an example that is tested. 
- Removed two unused imports that were never exported into the API or used internally in the `gaussian_quadrature` module, so that the two `#![allow(...)]` directives are no longer needed. Since it doesn't export anything rustdoc just generated a link …

Documentation tweaks: add docstrings to all submodules and quadrature structs, remove use of no longer needed language features from docs

---

src/jacobi/mod.rs

The `GaussJacobi` struct refers to itself as "Gauss-Laguerre" in the panic message that is issued if the input arguments `alpha` or `beta` are less than -1. This PR changes it to `Gauss-Jacobi` and adds a test for the panicking behavior.

Change 'Gauss-Laguerre' to 'Gauss-Jacobi' in a panic message in thrown by the `GaussJacobi` struct

---

Cargo.toml

Add categories to Config.toml as desired by the Rust API guide line, see #27 
Also extended the authors list on the same go
@JSorngard  I copied the name and email from another crate of yours, hope that's fine

Extend authors list, add category mathematics

---

Cargo.lock
Cargo.toml
src/hermite/mod.rs
src/jacobi/mod.rs
src/laguerre/mod.rs
src/legendre/mod.rs
src/lib.rs
src/midpoint/mod.rs
src/simpson/mod.rs

Also documents the feature.
Resolves #37.

Add a `serde` feature that implements `Serialize` and `Deserialize` for the quadrature rule structs

---

Cargo.lock
Cargo.toml

Turns out we don't need it! Slightly faster compile times y'all!

Remove the `macros` feature from nalgebra

---

CHANGELOG.md
src/jacobi/mod.rs

The docstring says
```rust
// initialize the quadrature rule.
let quad = GaussJacobi::init(10, -0.5, 0.0);
// numerically integrate e^-x / sqrt(1 + x).
let integral = quad.integrate(-1.0, 1.0, |x| (-x).exp());
```
But since `init` takes alpha first, which is the exponent of (1 - x) it's actually integrating e^-x / sqrt(1 - x). Inputting that into wolframalpha also gives the right answer, which should reduce the change that I'm making another sign error: <https://www.wolframalpha.com/input?i=integrate+e%5E%28-x%29%2Fsqrt%281-x%29+from+-1+to+1>

Fix sign error in GaussJacobi docstring

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/data_api.rs
src/hermite/iterators.rs
src/hermite/mod.rs
src/jacobi/iterators.rs
src/jacobi/mod.rs
src/laguerre/iterators.rs
src/laguerre/mod.rs
src/legendre/iterators.rs
src/legendre/mod.rs
src/lib.rs
src/midpoint/iterators.rs
src/midpoint/mod.rs
src/simpson/iterators.rs
src/simpson/mod.rs

This is my attempt at unifying the memory and using a macro to define the API to avoid a lot of typing.
I made two macros, the first takes in a struct with a `nodes_and_weights: Vec<(f64, f64)>` field, as well as names for some iterators and defines the functions
```rust
pub fn nodes(&self) -> QuadratureRuleNodes<'_> {...}
pub fn weights(&self) -> QuadratureRuleWeights<'_> {...}
pub fn iter(&self) -> QuadratureRuleIter<'_> {...}
pub fn as_node_weight_pairs(&self) -> &[(Node, Weight)] {...}
pub fn into_node_weight_pairs(self) -> Vec<(Node, Weight)> {...}
pub fn degree(&self) -> usize {...}
```
and the second defines those iterators as well as implements the `IntoIterator` trait on the struct.
To implement the API for a rule you just call the first macro in the same file as the struct is …

Implement the unified memory API using a macro

---

src/midpoint/iterators.rs
src/simpson/iterators.rs

All the other iterators implement this when possible, this just makes it consistent

Implement the `AsRef<[Node]>` trait for the iterators over Midpoint or Simpson nodes

---

src/hermite/mod.rs
src/jacobi/mod.rs

In the generation of nodes and weights for the Hermite and Jacobi quadrature rules there's a line of code that looks like
```rust
...
(eigen.eigenvectors.row(0).map(|x| x * x) * a_scalar_factor).iteration_function()
...
```
The map call results in a new matrix with each element squared, and then the matrix-scalar multiplication is most likely implemented by looping over the entire matrix and multiplying each element one by one by the scalar, so by merging this multiplication into the call to map there should be fewer loops needed and it should remove one allocation.

Merge the multiplication by the scale factor into the map call

---

src/jacobi/mod.rs

This removes a potential division by zero in `GaussJacobi::new` by panicking if `alpha <= -1 || beta <= -1` instead of `alpha < -1  || beta < -1`.

Fix div by zero

---

src/data_api.rs
src/hermite/iterators.rs
src/hermite/mod.rs
src/jacobi/iterators.rs
src/jacobi/mod.rs
src/laguerre/iterators.rs
src/laguerre/mod.rs
src/legendre/iterators.rs
src/legendre/mod.rs
src/midpoint/iterators.rs
src/midpoint/mod.rs
src/simpson/iterators.rs
src/simpson/mod.rs

This was a thought I had and wanted to run by you. Currently the iterators are defined in their own sub-sub-modules. But since we re-export the actual structs they are visible at the top level of the API and the docs, which means that if a user is looking at the docs of the crate where they can see the quadrature rule structs and wants to look at the iterators they actually have to go down two module levels, which seems a bit unnecessary.
This PR moves the definition of the iterators up one level to make the API less nested.

Move the definition of the iterators into the same module as where the quadrature rule structs are defined?

---

src/data_api.rs

Adds the `nth_back` function to the list of functions implemented in #63.
[Compare the massive assembly of `nth_back_derived` which uses the default implementation, with the short assembly of `nth_back_delegated` which uses the specialized implementation here](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYhJAdlKOAMngMmABy7gBGmMQgAEykAA6oCoR2DC5uHl6%2Bicm2AoHBYSyR0XFWmDapQgRMxATp7p4%2BlpjWeQzVtQQFoRFRsZY1dQ2ZzeZdPUUlsQCUlqgmxMjsHAD06wDUACoIeAob5qY2GwDudLQbCEwAbpgbBAh3WFRMJrQEG4IIAPrhTMgAaw2VBMDEqAg2WGIeFu6A24QAnvdHvdiExCAA6ACkGgAgocTMcALIIgCSBCiWIAzE4wBwmNTsBA0MR2CAFLQ8MsQCByZSaXSmKQNngqTFGTNqQAhHG42XrVbbXb7AnHM60C5XW4igh0/Z4FjxehsQRMdobVBUT4PX7/IFYejAM2YOFEZF3cYMdC1OGc8Jo4gI7F41UfEl …

 Implement the `nth_back` function for the iterators in terms of the already optimized version in the standard library

---

.github/workflows/rust.yml

The old versions use deprecated features, and there are new versions now, so this PR updates to those.

Update actions/checkout and codecov-action to v4

---

Cargo.lock
Cargo.toml
src/lib.rs

Thank you for developing `gauss-quad`!
It has been incredibly useful in my projects. (https://github.com/mattatz/curvo)
This pull request upgrades the `nalgebra` dependency to version 0.33 and also updates the version of the crate published by this repository.
This upgrade ensures compatibility with the latest features and improvements offered by nalgebra 0.33.

Upgrade nalgebra to 0.33.

---

README.md

This adds syntax highlighting to the  README for clarity.

Add rust syntax highlighting to README

---

Cargo.toml

I just realized that my email link in `Cargo.toml` doesn't use the standard TOML formatting with angle brackets, so this PR just fixes that.

Fix email toml format

---

src/laguerre/mod.rs

When I modified the number of nodes here, I forgot to change the comment above it :(

Fix error in docstring example of `GaussLaguerre`

---

src/lib.rs

The way I wrote the time complexity in the multiple-integral example is a bit cluttered. This PR simplifies it by using a [cubed symbol](https://symbolsdb.com/cubed-symbol) instead of writing ^(3).

Write the time complexity more clearly

---

CHANGELOG.md

This PR clarifies that the `par_integrate` function is added to the quadrature rule structs themselves when the `rayon` feature is enabled. Also makes them items.

Clarify changes of 0.2.1 in cangelog

---

CHANGELOG.md

Add a note to the log about the addition of the `par_new` function to `GaussLegendre`.

Add note about `par_new` to log

---

README.md

In the rest of the readme n is not an item, which is appropriate since we aren't talking about a program parameter, but a mathematical concept. This PR corrects that I wrote `n` in #86.

Correct itemization from #86

---

src/data_api.rs

Those docs included links to macros that were removed, and used the wrong names for macros that still exist.

Correct links in `data_api` module docs

---

src/simpson/mod.rs

This PR makes the sums over the edges and midpoints in the `Simpson::par_integrate` function able to run in parallel with each other by using [`rayon::join`](https://docs.rs/rayon/latest/rayon/fn.join.html). This speeds up the benchmarks by up to 37% on my machine:
The effect is largest on the benchmarks with small degrees where a single sum is not enough to saturate multiple cores, larger degrees only see a small improvement:

Let the sums over edges and midpoints in `Simpson::par_integrate` potentially run in parallel

---

README.md
src/hermite/mod.rs
src/jacobi/mod.rs
src/laguerre/mod.rs
src/legendre/mod.rs
src/lib.rs
src/midpoint/mod.rs
src/simpson/mod.rs

This PR adds links to the corresponding wikipedia page for each quadrature rule.

Add wikipedia links to the docs of each struct.

---

src/hermite/mod.rs
src/jacobi/mod.rs
src/laguerre/mod.rs
src/legendre/mod.rs
src/lib.rs
src/midpoint/mod.rs
src/simpson/mod.rs

It turns out that it's much cleaner that way because the rule names are first seen in the docs in the table at the start.

Move wiki links to the beginning of the crate docs instead of the structs

---

src/chebyshev/mod.rs

This aligns it with the other modules.

Remove the wikipedia link in the module docs of the chebyshev module

---

.github/workflows/rust.yml

This way there's fewer CI jobs to keep track of in the rust.yml file.

Merge stable and beta test CI jobs into one using a gihub actions matrix

---

README.md
src/chebyshev/mod.rs
src/hermite/mod.rs
src/jacobi/mod.rs
src/laguerre/mod.rs
src/legendre/mod.rs
src/lib.rs
src/midpoint/mod.rs
src/simpson/mod.rs

Change the `integrand` argument from `Fn` to `FnMut`.
Some integrands need to collect temporary results in a `Vec<f64>`. Making a new allocation can be e.g. an order of magnitude slower than the actual computation, so it may be very beneficial to re-use this scratch space across calls to the integrand.
However, the type signature is currently `Fn` which precludes this optimization. (this can be hacked around with `Rc` but it is unnatural.)
Since `fn integrate` is actually single-threaded, there is no reason not to use `FnMut` here. `FnMut` is a less restrictive bound than `Fn`, so this is a non-breaking change.
See more on this topic: https://doc.rust-lang.org/std/ops/trait.Fn.html
```
Since both FnMut and FnOnce are supertraits of Fn, any instance of Fn can be used as a parameter where a …
```

allow stateful integrands with `fn integrate`

---

src/data_api.rs

This skips iterating through the entire iterator if `last` is called. It's an iterator over a slice, so it should not really result in any assembly improvements, but this fulfills the suggestion of a clippy lint added in rust 1.86.

Implement `Iterator::last` by calling `DoubleEndedIterator::next_back` where applicable

---

CHANGELOG.md

Removes some unnecessary whitespace and adds a heading to the file.

Lint the changelog with `markdownlint`

---

src/lib.rs

This just adds the information that it's a good idea to aim for a degree such that 2*deg - 1 is at least as large that largest degree polynomial one might want to integrate with the rule.

Not what degree to select in the crate docs

---

.github/workflows/rust.yml

It does this by running `cargo doc --all-features` on the nightly compiler with the `RUSTDOCFLAGS` env var set to `--cfg docsrs` and warnings set to deny.

Add a CI job that mimics the doc generation on docs.rs

---

README.md

Completes https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive.
This does not change the licensing of the software or any contributions, it just makes that information clear.

Add license info to readme

---

README.md

This way, regardless of whether you are reading about the crate on crates.io or github.com there is a link at the top to take you to the other one.

Add a badge that takes you to the repo when clicked

---

src/data_api.rs
src/midpoint/mod.rs
src/simpson/mod.rs

This stores the degree instead of a `Vec` of nodes.

Implement `Simpson` or `Midpoint` without allocating

---

Cargo.toml

The publishing process removes the "[[bench]]" sections of the Cargo.toml if they are excluded, so this doesn't break the crate.

Don't package the benchmarks to crates.io

---

.github/workflows/rust.yml
Cargo.lock
src/lib.rs

Some CI jobs have started failing due to the API for the dtaolnay/rust-toolchain action changing, this PR fixes that. It also removes the use of the `doc_auto_cfg` nightly features since that was merged into the `doc_cfg` feature.

Fix failing CI jobs
